// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlpONb7YJG8bV7rxszpoCHI7weOS6NW58',
    appId: '1:772039404460:web:5ddd33dc7db82c1f51e809',
    messagingSenderId: '772039404460',
    projectId: 'chat-room-edcb6',
    authDomain: 'chat-room-edcb6.firebaseapp.com',
    storageBucket: 'chat-room-edcb6.appspot.com',
    measurementId: 'G-7KNJVRHT39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwPQTfqK2v610ZNINtgdiF6owudHNXv3Y',
    appId: '1:772039404460:android:fb0bc98669de225d51e809',
    messagingSenderId: '772039404460',
    projectId: 'chat-room-edcb6',
    storageBucket: 'chat-room-edcb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP6mnkz4QLV8x1gW-nCBlhTBgT9LRQ2Bo',
    appId: '1:772039404460:ios:f83c7ad592490c2a51e809',
    messagingSenderId: '772039404460',
    projectId: 'chat-room-edcb6',
    storageBucket: 'chat-room-edcb6.appspot.com',
    androidClientId: '772039404460-98mesf71pbhbtvn1ea0k73m4au4vccfc.apps.googleusercontent.com',
    iosClientId: '772039404460-jffl8e5k8ffso0rh07nn7b6q2ivml2av.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatRoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP6mnkz4QLV8x1gW-nCBlhTBgT9LRQ2Bo',
    appId: '1:772039404460:ios:f83c7ad592490c2a51e809',
    messagingSenderId: '772039404460',
    projectId: 'chat-room-edcb6',
    storageBucket: 'chat-room-edcb6.appspot.com',
    androidClientId: '772039404460-98mesf71pbhbtvn1ea0k73m4au4vccfc.apps.googleusercontent.com',
    iosClientId: '772039404460-jffl8e5k8ffso0rh07nn7b6q2ivml2av.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatRoom',
  );
}
